development:
  dialect: "mysql"
  database: "owl_power_dev"
  host: "localhost"
  port: "3306"
  user: "root"
  password: ""
  encoding: "utf8mb4_general_ci"

test:
  url: {{envOr "TEST_DATABASE_URL" "mysql://root:root@(localhost:3306)/owl_power_test?parseTime=true&multiStatements=true&readTimeout=1s"}}

production:
  url: {{envOr "DATABASE_URL" "mysql://root:root@(localhost:3306)/owl_power?parseTime=true&multiStatements=true&readTimeout=1s"}}
